# Limpeza e preparação de dados para análise

Este notebook tem a por finalidade a preparação de um DataSet para posterior análise de dados.

In [1]:
# importando bibliotecas
import pandas as pd
import numpy as np
from summarytools import dfSummary

## 1 - Carregando os dados

In [2]:
# Lendo os dados
open_masc = pd.read_csv('data/women_open_21.1.csv', sep=',', low_memory=False)

## 2 - Visualizando dados
Essa visualização é importante para compreender o que precisa ser feito no dataset.

Verifica-se que algumas colunas de valores estão em string e precisam ser convertidos para numéricos para possibilitar que os calculos sejam feitos.

Há uma coluna que condensa dois dados, peso e altura do atleta, deverá ser convertida em duas colunas.

Há outras colunas que condensam duas informações, por exemplo, a coluna '21.1' armazena dados da posição do atleta naquela prova e também do tempo em que o atleta concluiu a prova. *Vamos ficar apenas com a posição do atleta na prova*.


In [3]:
# Primeira visualização do Dataframe
open_masc.head()

Unnamed: 0    first_name   lastname  Placing        country      continent  \
0           0     TIA-CLAIR     TOOMEY        1      Australia        Oceania   
1           1          EMMA       CARY        2  United States  North America   
2           2          KARA   SAUNDERS        3      Australia        Oceania   
3           3  KRISTI ERAMO  O'CONNELL        4  United States  North America   
4           4       MALLORY    O'BRIEN        5  United States  North America   

      Age                        affiliate Height and Weight  points  \
0  Age 27          CrossFit East Nashville    163 cm | 58 kg      26   
1  Age 17  Perform Overcome Excel CrossFit    64 in | 140 lb      66   
2  Age 31                    CrossFit Carv   162 cm | 158 lb     111   
3  Age 32                 CrossFit Polaris    62 in | 132 lb     189   
4  Age 17              Lion Brave CrossFit    63 in | 145 lb     211   

            21.1 21.1 time           21.2 21.2 time         21.3 21.3 time  \
0    6th (11:21)  605 reps    11th (9:26)  225 reps   1st (7:37)  180 reps   
1   14th (11:48)  605 reps     1st (8:51)  225 reps  14th (8:28)  180 reps   
2   63rd (13:11)  605 reps    23rd (9:42)  225 reps  20th (8:41)  180 reps   
3  121st (13:47)  605 reps    21st (9:41)  225 reps   4th (7:47)  180 reps   
4    4th (11:06)  605 reps  163rd (10:38)  225 reps   2nd (7:38)  180 reps   

             21.4                   weight  
0   8th (230 lbs)  Weight lifted: 230 lbs.  
1  37th (218 lbs)  Weight lifted: 218 lbs.  
2   5th (232 lbs)  Weight lifted: 232 lbs.  
3  43rd (217 lbs)  Weight lifted: 217 lbs.  
4  42nd (217 lbs)  Weight lifted: 217 lbs.

In [4]:
# Verificando o "tamanho" do df
open_masc.shape

(108600, 18)

In [5]:
open_masc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108600 entries, 0 to 108599
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype 
---  ------             --------------   ----- 
 0   Unnamed: 0         108600 non-null  int64 
 1   first_name         108599 non-null  object
 2   lastname           108597 non-null  object
 3   Placing            108600 non-null  int64 
 4   country            108600 non-null  object
 5   continent          108600 non-null  object
 6   Age                108600 non-null  object
 7   affiliate          93538 non-null   object
 8   Height and Weight  50325 non-null   object
 9   points             108600 non-null  int64 
 10  21.1               108600 non-null  object
 11  21.1 time          8349 non-null    object
 12  21.2               108600 non-null  object
 13  21.2 time          50690 non-null   object
 14  21.3               108600 non-null  object
 15  21.3 time          8209 non-null    object
 16  21.4               1

In [6]:
# Primeira descrição dos dados numéricos, 
open_masc.describe()

Unnamed: 0        Placing         points
count  108600.000000  108600.000000  108600.000000
mean    54299.500000   54289.647459  211080.913444
std     31350.263954   31334.182357  107166.944901
min         0.000000       1.000000      26.000000
25%     27149.750000   27150.750000  120400.750000
50%     54299.500000   54300.500000  224044.500000
75%     81449.250000   81450.250000  303278.250000
max    108599.000000  108565.000000  374151.000000

In [7]:
# Verificando quais são as colunas originais do df
open_masc.columns

Index(['Unnamed: 0', 'first_name', 'lastname', 'Placing', 'country',
       'continent', 'Age', 'affiliate', 'Height and Weight', 'points', '21.1',
       '21.1 time', '21.2', '21.2 time', '21.3', '21.3 time', '21.4',
       'weight'],
      dtype='object')

## 3 - Tratando colunas

### 3.1 - Renomeando as colunas

In [8]:
open_masc =  open_masc.rename(columns={'Unnamed: 0': 'index', 'weight': 'weight_lifted', 'Age': 'age', 'Placing':'placing'})


### 3.2 - Separando as colunas de altura e peso do atleta
Ambas as colunas são dados numéricos.

Unidade de de medidas: peso(Kg), altura(cm)

#### Altura do atleta

In [9]:
open_masc['height'] = open_masc['Height and Weight']

In [10]:
def define_height(value):
    x = None
    if type(value) == str:
        a = value.split()
        if a[1] == 'in':
            x = int(a[0]) * 2.54
            x = round(x,2)
        elif a[1] == 'cm':
            x = int(a[0])
            x = round(x,2)
    return x

In [11]:
open_masc['height'] = open_masc['height'].apply(define_height)

#### Peso do atleta

In [12]:
open_masc['weight'] = open_masc['Height and Weight']

In [13]:
def define_weight(value):
    x = None
    if type(value) == str:
        a = value.split()
        if a[-1] == 'lb':
            x = int(a[-2]) / 2.2
            x = round(x,2)
        elif a[-1] == 'kg':
            x = int(a[-2])
            x = round(x,2)
    return x

In [14]:
open_masc['weight'] = open_masc['weight'].apply(define_weight)

Removendo a coluna de peso e altura 

In [15]:
open_masc.drop(['Height and Weight'], axis=1, inplace=True)

In [16]:
open_masc.head()

index    first_name   lastname  placing        country      continent  \
0      0     TIA-CLAIR     TOOMEY        1      Australia        Oceania   
1      1          EMMA       CARY        2  United States  North America   
2      2          KARA   SAUNDERS        3      Australia        Oceania   
3      3  KRISTI ERAMO  O'CONNELL        4  United States  North America   
4      4       MALLORY    O'BRIEN        5  United States  North America   

      age                        affiliate  points           21.1 21.1 time  \
0  Age 27          CrossFit East Nashville      26    6th (11:21)  605 reps   
1  Age 17  Perform Overcome Excel CrossFit      66   14th (11:48)  605 reps   
2  Age 31                    CrossFit Carv     111   63rd (13:11)  605 reps   
3  Age 32                 CrossFit Polaris     189  121st (13:47)  605 reps   
4  Age 17              Lion Brave CrossFit     211    4th (11:06)  605 reps   

            21.2 21.2 time         21.3 21.3 time            21.4  \
0    11th (9:26)  225 reps   1st (7:37)  180 reps   8th (230 lbs)   
1     1st (8:51)  225 reps  14th (8:28)  180 reps  37th (218 lbs)   
2    23rd (9:42)  225 reps  20th (8:41)  180 reps   5th (232 lbs)   
3    21st (9:41)  225 reps   4th (7:47)  180 reps  43rd (217 lbs)   
4  163rd (10:38)  225 reps   2nd (7:38)  180 reps  42nd (217 lbs)   

             weight_lifted  height  weight  
0  Weight lifted: 230 lbs.  163.00   58.00  
1  Weight lifted: 218 lbs.  162.56   63.64  
2  Weight lifted: 232 lbs.  162.00   71.82  
3  Weight lifted: 217 lbs.  157.48   60.00  
4  Weight lifted: 217 lbs.  160.02   65.91

### 3.3 - Transformando a coluna de idade em numérico

Durante o processo para realizar a transformação da coluna idade (de string para numérico) observou-se inconsistência nos dados da linha 57645, optando-se pela remoção da mesma

In [17]:
open_masc.iloc[57645]

index                             57645
first_name                      JESSICA
lastname                        BALLARD
placing                           57646
country                       Australia
continent                       Oceania
age                              Age 30
affiliate            CrossFit Dauntless
points                           237715
21.1                 43056th (179 reps)
21.1 time                           NaN
21.2                64541st (14:46 - s)
21.2 time                      225 reps
21.3             59769th (135 reps - s)
21.3 time                           NaN
21.4               70349th (84 lbs - s)
weight_lifted    Weight lifted: 84 lbs.
height                              NaN
weight                              NaN
Name: 57645, dtype: object

In [18]:
open_masc.drop(labels=57645, axis=0, inplace=True, errors='raise')

In [19]:
def transforma_idade(texto):
    if texto == "":
        x = 0
    else:
        texto.split(" ")
        x = texto[1]
    return(texto[-2:])

In [20]:
open_masc['age'] = open_masc['age'].apply(transforma_idade)


In [21]:
# Convertendo a coluna age (idade) de 'string' para numérico
open_masc['age'] = pd.to_numeric(open_masc['age'])


#### 3.4 - Tratando os resultados das provas 

In [22]:
open_masc = open_masc.drop(labels='21.1 time', axis=1)
open_masc = open_masc.drop(labels='21.2 time', axis=1)
open_masc = open_masc.drop(labels='21.3 time', axis=1)
open_masc.columns

Index(['index', 'first_name', 'lastname', 'placing', 'country', 'continent',
       'age', 'affiliate', 'points', '21.1', '21.2', '21.3', '21.4',
       'weight_lifted', 'height', 'weight'],
      dtype='object')

In [23]:
# Incluindo texto nos campos nulos de acordo com a coluna
values = {'21.1': '0', '21.2': '0', '21.3': '0', '21.4': '0'}
open_masc.fillna(value = values, inplace=True) 

In [24]:
open_masc.head()

index    first_name   lastname  placing        country      continent  age  \
0      0     TIA-CLAIR     TOOMEY        1      Australia        Oceania   27   
1      1          EMMA       CARY        2  United States  North America   17   
2      2          KARA   SAUNDERS        3      Australia        Oceania   31   
3      3  KRISTI ERAMO  O'CONNELL        4  United States  North America   32   
4      4       MALLORY    O'BRIEN        5  United States  North America   17   

                         affiliate  points           21.1           21.2  \
0          CrossFit East Nashville      26    6th (11:21)    11th (9:26)   
1  Perform Overcome Excel CrossFit      66   14th (11:48)     1st (8:51)   
2                    CrossFit Carv     111   63rd (13:11)    23rd (9:42)   
3                 CrossFit Polaris     189  121st (13:47)    21st (9:41)   
4              Lion Brave CrossFit     211    4th (11:06)  163rd (10:38)   

          21.3            21.4            weight_lifted  height  weight  
0   1st (7:37)   8th (230 lbs)  Weight lifted: 230 lbs.  163.00   58.00  
1  14th (8:28)  37th (218 lbs)  Weight lifted: 218 lbs.  162.56   63.64  
2  20th (8:41)   5th (232 lbs)  Weight lifted: 232 lbs.  162.00   71.82  
3   4th (7:47)  43rd (217 lbs)  Weight lifted: 217 lbs.  157.48   60.00  
4   2nd (7:38)  42nd (217 lbs)  Weight lifted: 217 lbs.  160.02   65.91

In [25]:
def define_posicao(p):
    p = p.split(" ")
    x = p[0].strip()
    if ('th' or 'nd' or 'st' or 'rd' in x):
        x = x.replace('th', '')
        x = x.replace('nd', '')
        x = x.replace('st', '')
        x = x.replace('rd', '')
    return x

In [26]:
open_masc['21.1'] = open_masc['21.1'].apply(define_posicao)
open_masc['21.2'] = open_masc['21.2'].apply(define_posicao)
open_masc['21.3'] = open_masc['21.3'].apply(define_posicao)
open_masc['21.4'] = open_masc['21.4'].apply(define_posicao)
open_masc['21.1'] = pd.to_numeric(open_masc['21.1'])
open_masc['21.2'] = pd.to_numeric(open_masc['21.2'])
open_masc['21.3'] = pd.to_numeric(open_masc['21.3'])
open_masc['21.4'] = pd.to_numeric(open_masc['21.4'])

### 3.5 - Transformando a coluna de peso levantado
Considerando unidade de medida Kg

In [27]:
open_masc.head()

index    first_name   lastname  placing        country      continent  age  \
0      0     TIA-CLAIR     TOOMEY        1      Australia        Oceania   27   
1      1          EMMA       CARY        2  United States  North America   17   
2      2          KARA   SAUNDERS        3      Australia        Oceania   31   
3      3  KRISTI ERAMO  O'CONNELL        4  United States  North America   32   
4      4       MALLORY    O'BRIEN        5  United States  North America   17   

                         affiliate  points  21.1  21.2  21.3  21.4  \
0          CrossFit East Nashville      26     6    11     1   8.0   
1  Perform Overcome Excel CrossFit      66    14     1    14  37.0   
2                    CrossFit Carv     111    63    23    20   5.0   
3                 CrossFit Polaris     189   121    21     4  43.0   
4              Lion Brave CrossFit     211     4   163     2  42.0   

             weight_lifted  height  weight  
0  Weight lifted: 230 lbs.  163.00   58.00  
1  Weight lifted: 218 lbs.  162.56   63.64  
2  Weight lifted: 232 lbs.  162.00   71.82  
3  Weight lifted: 217 lbs.  157.48   60.00  
4  Weight lifted: 217 lbs.  160.02   65.91

In [28]:
# Preenchendo pesos nullos com valor zero, por que considera-se que o atleta não realizou a prova
open_masc['weight_lifted'] = open_masc['weight_lifted'].fillna('0')

In [29]:
open_masc.tail()

index first_name lastname  placing         country      continent  \
108595  108595   GEORGINA  NOELLEN   108565         Germany         Europe   
108596  108596     STACEY    MAIDA   108565   United States  North America   
108597  108597      FIONA    STEEL   108565  United Kingdom         Europe   
108598  108598    RACHAEL   BUTLER   108565          Canada  North America   
108599  108599    VALERIA  MONTERO   108565   United States  North America   

        age             affiliate  points   21.1   21.2   21.3      21.4  \
108595   32        CrossFit Neuss  374151  94308  90537  80806  108500.0   
108596   36  CrossFit Five Points  374151  94308  90537  80806  108500.0   
108597   31                   NaN  374151  94308  90537  80806  108500.0   
108598   34                   NaN  374151  94308  90537  80806  108500.0   
108599   21                   NaN  374151  94308  90537  80806  108500.0   

       weight_lifted  height  weight  
108595             0   166.0   54.00  
108596             0   165.1   78.18  
108597             0     NaN     NaN  
108598             0     NaN   59.09  
108599             0   152.4     NaN

In [30]:
# Iniciando o processo para converter weight_lift para numerico
# Função para remover a string 'lbs' e converter peso para quilos
def substitui_texto(value):
    value = value.replace('Weight lifted: ', '')
    if ('l' in value):
        x = value.replace(' lbs', '')
    elif ('k' in value):
        x = value.replace(' kg', '')
    else:
        x = value
    x = float(x) / 2.205
    
    return(round(x,2))

In [31]:
#Funaçao para substituir valores inválidos por peso zero
def remove_peso_invalido(value):
    if ('(' in value):
        value = '0'
    return value

In [32]:
open_masc['weight_lifted'] = open_masc['weight_lifted'].apply(remove_peso_invalido)

In [33]:
open_masc['weight_lifted'] = open_masc['weight_lifted'].apply(substitui_texto)


In [34]:
# Convertendo a coluna weight lifted de 'string' para numérico
open_masc['weight_lifted'] = pd.to_numeric(open_masc['weight_lifted'])

In [35]:
open_masc['weight_lifted']

0         104.31
1          98.87
2         105.22
3          98.41
4          98.41
           ...  
108595      0.00
108596      0.00
108597      0.00
108598      0.00
108599      0.00
Name: weight_lifted, Length: 108599, dtype: float64

In [36]:
import numpy as np

In [37]:
c = max(open_masc['weight_lifted'])
index = np.where(open_masc['weight_lifted'] == c)
outlier = open_masc.iloc[index]

In [38]:
print("Nota: O atleta", open_masc['index'].iloc[100332], "apresenta dados inconsistentes referentes ao seu levantamento de peso")
display(outlier)


Nota: O atleta 100333 apresenta dados inconsistentes referentes ao seu levantamento de peso


index first_name lastname  placing country continent  age affiliate  \
83957  83957       NADA  ELARABY    83958   Egypt    Africa   31       NaN   

       points   21.1   21.2   21.3     21.4  weight_lifted  height  weight  
83957  309900  92052  90537  74680  52631.0        2501.59     NaN     NaN

## 4 - Preenchendo missings
Preencher strings que estão faltando (como nome, país de origem, afiliação, etc). Dadas as características dos dados, optou-se por fazer o preenchimento dos campos que estão vazios ou nullos. Por exemplo, nas colunas referentes ao resultado de uma determinada prova em específico (como a 21.3 ou 21.2) o fato de não ter sido atribuído um valor, indica que o atleta não realizou a prova, portanto atribuiu-se, conforme conveniente, valor zero. Na coluna de afiliação os missings foram tratados como "não afiliados", pois entende-se que se tratam de atletas que treinam em academias próprias ou não afiliada à Crossfit porém que obtiveram o direito de validar suas provas em local licenciado.

In [39]:
# Conferindo os continentes listados, 
continent = np.array(open_masc['continent'])
unique_continent = np.unique(continent)
print(unique_continent)

['Africa' 'Asia' 'Europe' 'North America' 'Oceania' 'South America']


In [40]:
# Visualizando todos os países listados
country = np.array(open_masc['country'])
unique_country = np.unique(country)
print("Total de países participantes: ", len(unique_country))
print(unique_country)

Total de países participantes:  145
['Albania' 'Algeria' 'Andorra' 'Angola' 'Antigua and Barbuda' 'Argentina'
 'Armenia' 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain'
 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Bhutan' 'Bolivia'
 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'Brunei Darussalam'
 'Bulgaria' 'Cambodia' 'Cameroon' 'Canada' 'Chile' 'China' 'Colombia'
 'Costa Rica' 'Croatia' 'Cyprus' 'Czech Republic' 'Denmark'
 'Dominican Republic' 'Ecuador' 'Egypt' 'El Salvador' 'Estonia' 'Fiji'
 'Finland' 'France' 'Georgia' 'Germany' 'Ghana' 'Greece' 'Grenada'
 'Guatemala' 'Guyana' 'Haiti' 'Honduras' 'Hungary' 'Iceland' 'India'
 'Indonesia' 'Iran' 'Iraq' 'Ireland' 'Israel' 'Italy' 'Jamaica' 'Japan'
 'Jordan' 'Kazakhstan' 'Kenya' 'Korea, Republic of' 'Kosovo' 'Kuwait'
 'Latvia' 'Lebanon' 'Libya' 'Liechtenstein' 'Lithuania' 'Luxembourg'
 'Macedonia' 'Madagascar' 'Malaysia' 'Malta' 'Mauritius' 'Mexico'
 'Micronesia' 'Moldova' 'Mongolia' 'Montenegro' 'Morocco' 'Mozambique'


In [41]:
# Verificando onde estão os dados nulos
open_masc.isnull().sum()

index                0
first_name           1
lastname             3
placing              0
country              0
continent            0
age                  0
affiliate        15062
points               0
21.1                 0
21.2                 0
21.3                 0
21.4                 1
weight_lifted        0
height           62867
weight           62517
dtype: int64

A coluna 'first_name' se refere ao primeiro nome do atleta conforme cadastrado no site da Crossfit Games, considerando que apenas um atleta apresenta missing nessa colunas e o atleta possui todos os outros dados consistentes, optou-se por atribuir o valor '-' à essa variável faltante.

A coluna 'last_name' se refere ao sobrenome do atleta conforme cadastrado no site da Crossfit Games, considerando que todos os atletas que não possuem sobrenome cadastrado possuem todos os outros valores consistentes optou-se por preservá-los e atribuir o valor '-' à essa variável faltante.

Os atletas não afiliados recebrão o valor 'not_affiliate' na coluna respectiva

Nota-se que existe um número considerável de atletas cujos dados de peso e altura não foram informados, visando resguardar os outros dados referentes aos resultados dos atletas optou-se por atribuir o valor "uninformed" aos respectivos casos.

In [42]:
# Encontrando quem tem first_name nulo
open_masc[pd.isna(open_masc['first_name'])]

index first_name lastname  placing country continent  age  \
67999  67999        NaN   ZHUANG    67999   China      Asia   41   

           affiliate  points   21.1   21.2   21.3     21.4  weight_lifted  \
67999  CrossFit Wusi  269055  59389  74228  63733  71705.0          35.83   

       height  weight  
67999   163.0    55.0

In [43]:
# Encontrando quem tem lastname nulo
open_masc[pd.isna(open_masc['lastname'])]

index first_name lastname  placing             country      continent  \
947      947      LEXIA      NaN      948       United States  North America   
32974  32974       HARA      NaN    32975  Korea, Republic of           Asia   
50854  50854   SAMANTHA      NaN    50855       United States  North America   

       age           affiliate  points   21.1   21.2   21.3     21.4  \
947     29        CrossFit MKT    7966     48    187   1139   6592.0   
32974   34  CrossFit Apgujeong  141834  25958  48231  25658  41987.0   
50854   37        CrossFit MFP  209116  41081  48244  57770  62021.0   

       weight_lifted  height  weight  
947            71.20     NaN     NaN  
32974          47.62     NaN     NaN  
50854          45.35     NaN     NaN

In [44]:
# Incluindo texto nos campos nulos de acordo com a coluna
values = {'lastname': '-', 'first_name': '-', 'affiliate': 'not_affiliate', 'height': 'uninformed', 'weight': 'uninformed'}
open_masc.fillna(value = values, inplace=True) 

### 4.1 - Convertendo colunas de dados categóricos
e o indíce em String

In [45]:
open_masc['continent'] = open_masc['continent'].astype("category")
open_masc['country'] = open_masc['country'].astype("category")
open_masc['affiliate'] = open_masc['affiliate'].astype("category")

In [46]:
open_masc['index'] = open_masc['index'].astype("str")

## 5 - Verificando a qualidade dos dados


In [47]:
open_masc.isna().sum()
# Nenhum valor null

index            0
first_name       0
lastname         0
placing          0
country          0
continent        0
age              0
affiliate        0
points           0
21.1             0
21.2             0
21.3             0
21.4             1
weight_lifted    0
height           0
weight           0
dtype: int64

In [48]:
# Verificando consistencia dos dados - INCONSISTENTE
# peso_maximo = open_masc['weight_lifted'].max()
# peso_maximo

In [49]:
dfSummary(open_masc)

In [50]:
#Salvando o dataframe para análise
open_masc.to_csv("data/crossfit_open_feminino_2021.csv", index=False)